### ISSUE TITLE
メモ新規作成の API 実装

### ISSUE THREAD

**Issue by YutaNakamizo** [YutaNakamizo/notewebapp-backend#3]
`/api/notes` への **PUT** リクエストを受けるクラスを実装. (データベースへの接続はなし.)

Path:
`/api/notes`

Method:
**PUT**

Request Body:
```json
{
  "title": "(String 型)",
  "body": "(String 型)"
}
```

Response Body:
```json
{
  "id": "String 型",
  "dateCreated": "Int 型 とか long 型",
  "status": "success (固定値)",
  "archived": false,
  "title": "String 型",
  "body": "String 型"
}
```

- メモの ID を作る. 方法は何でも良いが, たとえば `タイトル + 作成日時 (秒表記) + ランダム値 (4 桁程度)` のように繋げた文字列について RSA-SHA256 でハッシュ値を作り, その先頭 24 文字を ID として採用する等.

**Comment by Tororokombu** [comment]
【質問】このクラスは(今回の＃3の実装で、そして最終的に)どこまでの処理を行うの？？

DBへの接続が無いということは、JSのプログラムが受け取った入力値が渡された時に、
Response Bodyクラスの実体を１つ作ればよいだけ？？？
（ID生成、日時取得などのメソッドを積む予定）

**Comment by YutaNakamizo** [comment]
1. [#3] Request Body の受取
1. [#3] ID の生成 (ハッシュ値)
1. [#3] dateCreated の生成 (処理時の時刻)
1. [#8] DB への保存
1. [#3] Request Body の返送

その認識で大丈夫. #3 での実装は ID と dateCreated を新規に生成した上で, Request Body の中身をそのまま流用して Response Body を作るだけ. DB への接続は #8 でやる.

ちなみに最終的に返送する Response Body はインスタンスではなく単なる文字列 (JSON という形式).
`"{ \"id\": \"xxxxxxxxxxx\" ... }"` のように文字列として直接生成してもいいが, 一旦クラスを通して, 最後に変換するのも良いかもしれない.

Jackson っていうライブラリを使えば Json と Java のインスタンスを相互に変換できるらしい.
https://medium.com/@bau1537/jackson%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9Fjava%E3%81%A8json%E3%81%AE%E7%9B%B8%E4%BA%92%E5%A4%89%E6%8F%9B-a88dad6d8d54

**Comment by Tororokombu** [comment]
理解した！！

そのJSON形式でのデータ受け渡しの話は昨日調べてたら色々出てきたから認識はしてる。
使えたらなーと思ってるから調べておくね

ありがとう！！
