### ISSUE TITLE
メモ削除の API 実装

### ISSUE THREAD

**Issue by YutaNakamizo** [YutaNakamizo/notewebapp-backend#5]
`/api/notes/<note_id>` への **DELETE** リクエストを受けるクラスの実装. (データベースへの接続はなし.)

Path:
`/api/notes/<note_id>`

Method:
**DELETE**

Request Body:
(なし)

Response Body:
```json
{
  "archived": true,
  "id": "String 型",
  "dateCreated": "int 型 または long 型",
  "dateLastModified": "int 型 または long 型",
  "title": "String 型",
  "body": "String 型"
}
```

**Comment by Tororokombu** [comment]
これ削除って、archived変数を更新するだけ。。。。？？？？
